### ISSUE TITLE
Scrollable icon sidebar

### ISSUE THREAD

**Issue by zapotocnylubos** [DesignRevision/shards-dashboard-pro#1]
## Expected Behavior
Icon sidebar should be scrollable, when content is bigger than screen height.

## Current Behavior
Icon sidebar cant be scrolled to bottom when screen height is small.
Or there is many items in sidebar.

## Steps to Reproduce
go to [icon-sidebar-nav.html demo](https://designrevision.com/demo/shards-dashboards/icon-sidebar-nav.html)

in chrome:
- in settings change zoom to higher percentage, until some items in sidebar are not visible.
- try to scroll to bottom items

or just change your browser window height.

## Context (Environment)
Tested on Macbook 2017 13 inch
- chrome and safari - not working

Tested on Windows laptop Full hd diplay
- chrome - not working

**Comment by nickvasdev** [comment]
✅This issue has been fixed in 1.3.0.
