### ISSUE TITLE
Sidebar toggler on md (768px-991px) not working properly

### ISSUE THREAD

**Issue by zapotocnylubos** [DesignRevision/shards-dashboard-pro#2]
## Expected Behavior
Scenario 1
- "hamburger" toggler in top navbar should toggle visibility of sidebar on md size

Scenario 2
- "hamburger" toggler in top navbar should not be visible from md size up

## Current Behavior
"hamburger" toggler is visible on md size, **but does nothing** 

## Steps to Reproduce

- go to [demo site](https://designrevision.com/demo/shards-dashboards/)
- make your browser window width from 768px to 991px (Bootsrap default md breakpoints)
- try to click "hamburger" toggler located on right in top navbar

## Context (Environment)
"hamburger" toggler is useless in md sizes
from my opinion it should behave by "Scenario 1" or "Scenario 2" written above

**Comment by nickvasdev** [comment]
Thank you for submitting this bug! The fix for this issue will be released in the next update. 🙂

**Comment by nickvasdev** [comment]
✅This issue has been fixed in 1.3.0.
