### ISSUE TITLE
Login page not works on small devices (iPhone 5S/SE)

### ISSUE THREAD

**Issue by zapotocnylubos** [DesignRevision/shards-dashboard-pro#4]
## Expected Behavior
Login page should be responsive on small screens like iPhone 5S/SE

## Current Behavior
Login page is not responsive, not centered

## Steps to Reproduce
- go to [demo page - login](https://designrevision.com/demo/shards-dashboards/login.html)
- change browser window width to 320px

## Context (Environment)
I have tested on real hardware iPhone 5s and iPhone SE, none of them worked,
On my project I dont have sidebar active on login page, still dont works.

**Comment by nickvasdev** [comment]
Thank you for submitting this issue! I've managed to reproduced this issue and the fix will be released in the next update. 🙂

**Comment by nickvasdev** [comment]
✅This issue has been fixed in 1.3.0.
